### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by mery00pr** [shyamcody/spacy_streamlit_app#3]
I was using the app and it stopped working

**Comment by shyamcody** [comment]
I will take a look into it. Probably the app was inactive for too long and streamlit closed it.

**Comment by shyamcody** [comment]
Can you please check now? I have recompiled the code and now its running for me.

**Comment by mery00pr** [comment]
It is working, thank you!

**Comment by shyamcody** [comment]
you are welcome! can you please mail me at shyambhu20@gmail.com letting me know how you use it? would love to know my users.
